export const CONSTS = {
    page_size: 10,
    page_size_options: [10, 20, 50],
    icon_not_selected: 'icon_not_selected.png',
    icon_allow_types: ['png'],
    image_invalid: 'Ảnh không hợp lệ',
    icon_type: '.png',
    messages: {
        update_category_success: 'Cập nhật chủng loại thành công',
        update_category_fail: 'Cập nhật chủng loại thất bại',
        icon_not_found: 'Không tìm thấy icon',
        insert_category_success: 'Thêm mới chủng loại thành công',
        insert_category_fail: 'Thêm mới chủng loại thất bại',
        delete_category_success: 'Xóa chủng loại thành công',
        delete_category_fail: 'Xóa chủng loại thất bại',
        upload_icon_success: 'Tải lên icon thành công',
        upload_icon_fail: 'Tải lên icon thất bại',
        delete_icon_success: 'Xóa icon thành công',
        delete_icon_fail: 'Xóa icon thất bại',
        update_walettype_success: 'Cập nhật loại ví thành công',
        update_walettype_fail: 'Cập nhật loại ví thất bại',
        insert_walettype_success: 'Thêm mới loại ví thành công',
        insert_walettype_fail: 'Thêm mới loại ví thất bại',
        delete_walettype_success: 'Xóa loại ví thành công',
        delete_walettype_fail: 'Xóa loại ví thất bại',
    }
}