version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/money-lover/cicd
permissions:
  - object: /home/ec2-user/money-lover/cicd/scripts
    mode: 755
    pattern: "**"
hooks:
   AfterInstall:
     - location: scripts/after-install.sh
       runas: root